name: Crypto News Preprocessing Workflow

on:
  push:
    branches: [ main ]
    paths:
      - 'cryptonews_raw/**'
      - 'preprocessing/automate_Demahesta.py'
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  preprocess_data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy nltk scikit-learn
          
          # Specify the NLTK_DATA directory so that NLTK knows where to look.
          echo "NLTK_DATA=$(pwd)/nltk_data" >> $GITHUB_ENV
          mkdir -p $(pwd)/nltk_data

          # Download NLTK packages using the downloader, one at a time for log clarity
          python -m nltk.downloader -d $(pwd)/nltk_data punkt
          python -m nltk.downloader -d $(pwd)/nltk_data stopwords
          python -m nltk.downloader -d $(pwd)/nltk_data punkt_tab  

      - name: Run Preprocessing Script
        run: |
          cd preprocessing
          python automate_Demahesta.py

      - name: Upload Preprocessed Data
        uses: actions/upload-artifact@v4
        with:
          name: crypto-sentiment-data
          path: |
            preprocessing/preprocessed_data/
            preprocessing/preprocessed_artifacts/